name: Vermicious Dad
favicon: null
layout_spectrum: 0.24368
typography_spectrum: 0.4234630048740655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.7733723723795265
  saturation: 0.6602294095791876
  rhythmicContrast: 0.36608077003620565
purpose: []
